delete from [FUNCTION]

Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0001','Acknowledge Purchase Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0002','Enquire Purchase Order List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0003','Print Purchase Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0004','Create Delivery Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0005','Enquire Delivery Orders')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0006','Print Delivery Order Report')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0007','Acknowledge Purchase Contract')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0008','Enquire Purchase Contract List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0009','Print Purchase Contract')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0010','Process Quotations')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0011','Enquire Quotation')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0012','Print Quotations')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0013','Acknowledge Expedite Deliveries')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0014','Print Expedite Deliveries List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0015','Acknowledge Receipt Rejected Goods')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0016','Enquire Goods Rejection')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0017','Print Goods Rejection')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0018','Accept/Reject Purchase Order Acknowledgement')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0019','Enquire Purchase Order List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0020','Print Purchase Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0021','Purchase Order Acknowledge By Buyer')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0022','Enquire Purchase Contract List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0023','Print Purchase Contract')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0024','Create Request for Quotation')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0025','Enquire Quotation')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0026','Print Quotations')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0027','Purchase Order Expediting Process')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0028','View Shortage List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0029','Print Shortage Report')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0030','Expedite Deliver')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0031','Confirm Acknowledgement of Expedite Deliveries')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0032','Enquire Delivery Orders')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0033','Print Delivery Order Report')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0034','Register User')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0035','Maintain User')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0036','Reset Password')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0037','Update Profile')
