
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Client SAP proxy class
  /// </summary>
  [WebServiceBinding(Name="dummy.Binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
  [Serializable]
  public class SAPProxy6 : SAPClient
  {
    /// <summary>
    /// Initializes a new SAPProxy6.
    /// </summary>
    public SAPProxy6(){}

    /// <summary>
    /// Initializes a new SAPProxy6 with a new connection based on the specified connection string.
    /// </summary>
    /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
    public SAPProxy6(string connectionString) : base(connectionString){}

    /// <summary>
    /// Initializes a new SAPProxy6 instance and adds it to the given container.
    /// This allows automated connection mananged by VS component designer:
    /// If container is disposed, it will also dispose this SAPClient instance,
    /// which will dispose a contained connection if needed.
    /// </summary>
    /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
    public SAPProxy6(System.ComponentModel.IContainer container) : base(container) {}    
  
    /// <summary>
    /// Exception constant for ABAP-Exception RECORDNOTFOUND
    /// </summary>
    public const string Recordnotfound = "RECORDNOTFOUND";
   
    /// <summary>
    /// Remote Function Module ZRETRIEVEREQUISITION.  
    /// Retrieve Requisition Details
    /// </summary>
    /// <param name="Requisition_Header">Requisition Header - Work Area</param>
    /// <param name="Requisition_Item">Purchase Requisition Item - Work Area</param> 
    /// <exception cref="Recordnotfound"/>
    [RfcMethod(AbapName = "ZRETRIEVEREQUISITION")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZRETRIEVEREQUISITION",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZRETRIEVEREQUISITION",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZRETRIEVEREQUISITION.Response")]
    public virtual void Zretrieverequisition (

     [RfcParameter(AbapName = "REQUISITION_HEADER",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("REQUISITION_HEADER", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     ref ZREQN_HDRTable Requisition_Header,
     [RfcParameter(AbapName = "REQUISITION_ITEM",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("REQUISITION_ITEM", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     ref ZREQN_ITMTable Requisition_Item)
    {
        object[]results = null;
        results = this.SAPInvoke("Zretrieverequisition",new object[] {
                            Requisition_Header,Requisition_Item });
        Requisition_Header = (ZREQN_HDRTable) results[0];
        Requisition_Item = (ZREQN_ITMTable) results[1];

    }

  } 

}
