
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Material Stock Balance Details - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZMATL_STOCK" , Length = 79, Length2 = 144)]
  [Serializable]
  public class ZMATL_STOCK : SAPStructure
  {
   

    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 0, Offset2 = 0)]
    [XmlElement("MATNR", Form=XmlSchemaForm.Unqualified)]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "WERKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 18, Offset2 = 36)]
    [XmlElement("WERKS", Form=XmlSchemaForm.Unqualified)]
    public string Werks
    { 
       get
       {
          return _Werks;
       }
       set
       {
          _Werks = value;
       }
    }
    private string _Werks;


    /// <summary>
    /// Material Description
    /// </summary>
 
    [RfcField(AbapName = "MAKTX", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 22, Offset2 = 44)]
    [XmlElement("MAKTX", Form=XmlSchemaForm.Unqualified)]
    public string Maktx
    { 
       get
       {
          return _Maktx;
       }
       set
       {
          _Maktx = value;
       }
    }
    private string _Maktx;


    /// <summary>
    /// Valuated stock with unrestricted use
    /// </summary>
 
    [RfcField(AbapName = "LABST", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 62, Offset2 = 124)]
    [XmlElement("LABST", Form=XmlSchemaForm.Unqualified)]
    public Decimal Labst
    { 
       get
       {
          return _Labst;
       }
       set
       {
          _Labst = value;
       }
    }
    private Decimal _Labst;


    /// <summary>
    /// Stock in quality inspection
    /// </summary>
 
    [RfcField(AbapName = "INSME", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 69, Offset2 = 131)]
    [XmlElement("INSME", Form=XmlSchemaForm.Unqualified)]
    public Decimal Insme
    { 
       get
       {
          return _Insme;
       }
       set
       {
          _Insme = value;
       }
    }
    private Decimal _Insme;


    /// <summary>
    /// Base Unit of Measure
    /// </summary>
 
    [RfcField(AbapName = "MEINS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 76, Offset2 = 138)]
    [XmlElement("MEINS", Form=XmlSchemaForm.Unqualified)]
    public string Meins
    { 
       get
       {
          return _Meins;
       }
       set
       {
          _Meins = value;
       }
    }
    private string _Meins;

  }

}
