
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Purchase Order Header Text - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZORDER_ITMTXT" , Length = 274, Length2 = 548)]
  [Serializable]
  public class ZORDER_ITMTXT : SAPStructure
  {
   

    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Item Number of Purchasing Document
    /// </summary>
 
    [RfcField(AbapName = "EBELP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 10, Offset2 = 20)]
    [XmlElement("EBELP", Form=XmlSchemaForm.Unqualified)]
    public string Ebelp
    { 
       get
       {
          return _Ebelp;
       }
       set
       {
          _Ebelp = value;
       }
    }
    private string _Ebelp;


    /// <summary>
    /// Text ID
    /// </summary>
 
    [RfcField(AbapName = "TXTITM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 15, Offset2 = 30)]
    [XmlElement("TXTITM", Form=XmlSchemaForm.Unqualified)]
    public string Txtitm
    { 
       get
       {
          return _Txtitm;
       }
       set
       {
          _Txtitm = value;
       }
    }
    private string _Txtitm;


    /// <summary>
    /// Context string
    /// </summary>
 
    [RfcField(AbapName = "LTXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 255, Length2 = 510, Offset = 19, Offset2 = 38)]
    [XmlElement("LTXT", Form=XmlSchemaForm.Unqualified)]
    public string Ltxt
    { 
       get
       {
          return _Ltxt;
       }
       set
       {
          _Ltxt = value;
       }
    }
    private string _Ltxt;

  }

}
