
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Purchase Order Service Item Details - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZORDER_SRV" , Length = 85, Length2 = 150)]
  [Serializable]
  public class ZORDER_SRV : SAPStructure
  {
   

    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Item Number of Purchasing Document
    /// </summary>
 
    [RfcField(AbapName = "EBELP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 10, Offset2 = 20)]
    [XmlElement("EBELP", Form=XmlSchemaForm.Unqualified)]
    public string Ebelp
    { 
       get
       {
          return _Ebelp;
       }
       set
       {
          _Ebelp = value;
       }
    }
    private string _Ebelp;


    /// <summary>
    /// Entry sheet number
    /// </summary>
 
    [RfcField(AbapName = "LBLNI", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 15, Offset2 = 30)]
    [XmlElement("LBLNI", Form=XmlSchemaForm.Unqualified)]
    public string Lblni
    { 
       get
       {
          return _Lblni;
       }
       set
       {
          _Lblni = value;
       }
    }
    private string _Lblni;


    /// <summary>
    /// Short text
    /// </summary>
 
    [RfcField(AbapName = "KTEXT1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 25, Offset2 = 50)]
    [XmlElement("KTEXT1", Form=XmlSchemaForm.Unqualified)]
    public string Ktext1
    { 
       get
       {
          return _Ktext1;
       }
       set
       {
          _Ktext1 = value;
       }
    }
    private string _Ktext1;


    /// <summary>
    /// Purchase order quantity
    /// </summary>
 
    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 65, Offset2 = 130)]
    [XmlElement("MENGE", Form=XmlSchemaForm.Unqualified)]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;


    /// <summary>
    /// Net value of entry sheet
    /// </summary>
 
    [RfcField(AbapName = "PREIS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Length2 = 6, Decimals = 2, Offset = 72, Offset2 = 137)]
    [XmlElement("PREIS", Form=XmlSchemaForm.Unqualified)]
    public Decimal Preis
    { 
       get
       {
          return _Preis;
       }
       set
       {
          _Preis = value;
       }
    }
    private Decimal _Preis;


    /// <summary>
    /// Gross order value in PO currency
    /// </summary>
 
    [RfcField(AbapName = "BRTWR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 2, Offset = 78, Offset2 = 143)]
    [XmlElement("BRTWR", Form=XmlSchemaForm.Unqualified)]
    public Decimal Brtwr
    { 
       get
       {
          return _Brtwr;
       }
       set
       {
          _Brtwr = value;
       }
    }
    private Decimal _Brtwr;

  }

}
