
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/01/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Purchase Order Item Details - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZORDER_ITM" , Length = 232, Length2 = 434)]
  [Serializable]
  public class ZORDER_ITM : SAPStructure
  {
   

    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Item Number of Purchasing Document
    /// </summary>
 
    [RfcField(AbapName = "EBELP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 10, Offset2 = 20)]
    [XmlElement("EBELP", Form=XmlSchemaForm.Unqualified)]
    public string Ebelp
    { 
       get
       {
          return _Ebelp;
       }
       set
       {
          _Ebelp = value;
       }
    }
    private string _Ebelp;


    /// <summary>
    /// Item category in purchasing document
    /// </summary>
 
    [RfcField(AbapName = "PSTYP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 15, Offset2 = 30)]
    [XmlElement("PSTYP", Form=XmlSchemaForm.Unqualified)]
    public string Pstyp
    { 
       get
       {
          return _Pstyp;
       }
       set
       {
          _Pstyp = value;
       }
    }
    private string _Pstyp;


    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 16, Offset2 = 32)]
    [XmlElement("MATNR", Form=XmlSchemaForm.Unqualified)]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Short text
    /// </summary>
 
    [RfcField(AbapName = "TXZ01", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 34, Offset2 = 68)]
    [XmlElement("TXZ01", Form=XmlSchemaForm.Unqualified)]
    public string Txz01
    { 
       get
       {
          return _Txz01;
       }
       set
       {
          _Txz01 = value;
       }
    }
    private string _Txz01;


    /// <summary>
    /// Old material number
    /// </summary>
 
    [RfcField(AbapName = "BISMT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 74, Offset2 = 148)]
    [XmlElement("BISMT", Form=XmlSchemaForm.Unqualified)]
    public string Bismt
    { 
       get
       {
          return _Bismt;
       }
       set
       {
          _Bismt = value;
       }
    }
    private string _Bismt;


    /// <summary>
    /// Purchase order quantity
    /// </summary>
 
    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 92, Offset2 = 184)]
    [XmlElement("MENGE", Form=XmlSchemaForm.Unqualified)]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;


    /// <summary>
    /// Price Unit
    /// </summary>
 
    [RfcField(AbapName = "PEINH", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Offset = 99, Offset2 = 191)]
    [XmlElement("PEINH", Form=XmlSchemaForm.Unqualified)]
    public Decimal Peinh
    { 
       get
       {
          return _Peinh;
       }
       set
       {
          _Peinh = value;
       }
    }
    private Decimal _Peinh;


    /// <summary>
    /// Base Unit of Measure
    /// </summary>
 
    [RfcField(AbapName = "MEINS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 102, Offset2 = 194)]
    [XmlElement("MEINS", Form=XmlSchemaForm.Unqualified)]
    public string Meins
    { 
       get
       {
          return _Meins;
       }
       set
       {
          _Meins = value;
       }
    }
    private string _Meins;


    /// <summary>
    /// Net price in purchasing document (in document currency)
    /// </summary>
 
    [RfcField(AbapName = "NETPR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Length2 = 6, Decimals = 2, Offset = 105, Offset2 = 200)]
    [XmlElement("NETPR", Form=XmlSchemaForm.Unqualified)]
    public Decimal Netpr
    { 
       get
       {
          return _Netpr;
       }
       set
       {
          _Netpr = value;
       }
    }
    private Decimal _Netpr;


    /// <summary>
    /// Net order value in PO currency
    /// </summary>
 
    [RfcField(AbapName = "NETWR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 2, Offset = 111, Offset2 = 206)]
    [XmlElement("NETWR", Form=XmlSchemaForm.Unqualified)]
    public Decimal Netwr
    { 
       get
       {
          return _Netwr;
       }
       set
       {
          _Netwr = value;
       }
    }
    private Decimal _Netwr;


    /// <summary>
    /// Quantity of goods received
    /// </summary>
 
    [RfcField(AbapName = "WEMNG", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 118, Offset2 = 213)]
    [XmlElement("WEMNG", Form=XmlSchemaForm.Unqualified)]
    public Decimal Wemng
    { 
       get
       {
          return _Wemng;
       }
       set
       {
          _Wemng = value;
       }
    }
    private Decimal _Wemng;


    /// <summary>
    /// General Name
    /// </summary>
 
    [RfcField(AbapName = "KTEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 125, Offset2 = 220)]
    [XmlElement("KTEXT", Form=XmlSchemaForm.Unqualified)]
    public string Ktext
    { 
       get
       {
          return _Ktext;
       }
       set
       {
          _Ktext = value;
       }
    }
    private string _Ktext;


    /// <summary>
    /// Cost Center
    /// </summary>
 
    [RfcField(AbapName = "KOSTL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 145, Offset2 = 260)]
    [XmlElement("KOSTL", Form=XmlSchemaForm.Unqualified)]
    public string Kostl
    { 
       get
       {
          return _Kostl;
       }
       set
       {
          _Kostl = value;
       }
    }
    private string _Kostl;


    /// <summary>
    /// Order Number
    /// </summary>
 
    [RfcField(AbapName = "AUFNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 155, Offset2 = 280)]
    [XmlElement("AUFNR", Form=XmlSchemaForm.Unqualified)]
    public string Aufnr
    { 
       get
       {
          return _Aufnr;
       }
       set
       {
          _Aufnr = value;
       }
    }
    private string _Aufnr;


    /// <summary>
    /// Storage Location
    /// </summary>
 
    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 167, Offset2 = 304)]
    [XmlElement("LGORT", Form=XmlSchemaForm.Unqualified)]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;


    /// <summary>
    /// Asset class marked for deletion
    /// </summary>
 
    [RfcField(AbapName = "LOEKZ", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 171, Offset2 = 312)]
    [XmlElement("LOEKZ", Form=XmlSchemaForm.Unqualified)]
    public string Loekz
    { 
       get
       {
          return _Loekz;
       }
       set
       {
          _Loekz = value;
       }
    }
    private string _Loekz;


    /// <summary>
    /// Note text
    /// </summary>
 
    [RfcField(AbapName = "TXT01", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 60, Length2 = 120, Offset = 172, Offset2 = 314)]
    [XmlElement("TXT01", Form=XmlSchemaForm.Unqualified)]
    public string Txt01
    { 
       get
       {
          return _Txt01;
       }
       set
       {
          _Txt01 = value;
       }
    }
    private string _Txt01;

  }

}
