
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/01/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Purchase Order Goods Rejection Details - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZORDER_REJECT" , Length = 108, Length2 = 204)]
  [Serializable]
  public class ZORDER_REJECT : SAPStructure
  {
   

    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Item Number of Purchasing Document
    /// </summary>
 
    [RfcField(AbapName = "EBELP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 10, Offset2 = 20)]
    [XmlElement("EBELP", Form=XmlSchemaForm.Unqualified)]
    public string Ebelp
    { 
       get
       {
          return _Ebelp;
       }
       set
       {
          _Ebelp = value;
       }
    }
    private string _Ebelp;


    /// <summary>
    /// Number of Material Document
    /// </summary>
 
    [RfcField(AbapName = "MBLNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 15, Offset2 = 30)]
    [XmlElement("MBLNR", Form=XmlSchemaForm.Unqualified)]
    public string Mblnr
    { 
       get
       {
          return _Mblnr;
       }
       set
       {
          _Mblnr = value;
       }
    }
    private string _Mblnr;


    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 25, Offset2 = 50)]
    [XmlElement("MATNR", Form=XmlSchemaForm.Unqualified)]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "WERKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 43, Offset2 = 86)]
    [XmlElement("WERKS", Form=XmlSchemaForm.Unqualified)]
    public string Werks
    { 
       get
       {
          return _Werks;
       }
       set
       {
          _Werks = value;
       }
    }
    private string _Werks;


    /// <summary>
    /// Storage Location
    /// </summary>
 
    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 47, Offset2 = 94)]
    [XmlElement("LGORT", Form=XmlSchemaForm.Unqualified)]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;


    /// <summary>
    /// Account Number of Vendor or Creditor
    /// </summary>
 
    [RfcField(AbapName = "LIFNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 51, Offset2 = 102)]
    [XmlElement("LIFNR", Form=XmlSchemaForm.Unqualified)]
    public string Lifnr
    { 
       get
       {
          return _Lifnr;
       }
       set
       {
          _Lifnr = value;
       }
    }
    private string _Lifnr;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 61, Offset2 = 122)]
    [XmlElement("MENGE", Form=XmlSchemaForm.Unqualified)]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;


    /// <summary>
    /// Base Unit of Measure
    /// </summary>
 
    [RfcField(AbapName = "MEINS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 68, Offset2 = 130)]
    [XmlElement("MEINS", Form=XmlSchemaForm.Unqualified)]
    public string Meins
    { 
       get
       {
          return _Meins;
       }
       set
       {
          _Meins = value;
       }
    }
    private string _Meins;


    /// <summary>
    /// Amount in local currency
    /// </summary>
 
    [RfcField(AbapName = "DMBTR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 2, Offset = 71, Offset2 = 136)]
    [XmlElement("DMBTR", Form=XmlSchemaForm.Unqualified)]
    public Decimal Dmbtr
    { 
       get
       {
          return _Dmbtr;
       }
       set
       {
          _Dmbtr = value;
       }
    }
    private Decimal _Dmbtr;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "WAERS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 78, Offset2 = 144)]
    [XmlElement("WAERS", Form=XmlSchemaForm.Unqualified)]
    public string Waers
    { 
       get
       {
          return _Waers;
       }
       set
       {
          _Waers = value;
       }
    }
    private string _Waers;


    /// <summary>
    /// Posting Date in the Document
    /// </summary>
 
    [RfcField(AbapName = "BUDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 83, Offset2 = 154)]
    [XmlElement("BUDAT", Form=XmlSchemaForm.Unqualified)]
    public string Budat
    { 
       get
       {
          return _Budat;
       }
       set
       {
          _Budat = value;
       }
    }
    private string _Budat;


    /// <summary>
    /// Debit/Credit Indicator
    /// </summary>
 
    [RfcField(AbapName = "SHKZG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 91, Offset2 = 170)]
    [XmlElement("SHKZG", Form=XmlSchemaForm.Unqualified)]
    public string Shkzg
    { 
       get
       {
          return _Shkzg;
       }
       set
       {
          _Shkzg = value;
       }
    }
    private string _Shkzg;


    /// <summary>
    /// Reference Document Number
    /// </summary>
 
    [RfcField(AbapName = "XBLNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 92, Offset2 = 172)]
    [XmlElement("XBLNR", Form=XmlSchemaForm.Unqualified)]
    public string Xblnr
    { 
       get
       {
          return _Xblnr;
       }
       set
       {
          _Xblnr = value;
       }
    }
    private string _Xblnr;

  }

}
