
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{
  /// <summary>
  /// A typed collection of ZREQN_ITM elements.
  /// </summary>
  [Serializable]
  public class ZREQN_ITMTable : SAPTable 
  {
  
    /// <summary>
    /// Returns the element type ZREQN_ITM.
    /// </summary>
    /// <returns>The type ZREQN_ITM.</returns>
    public override Type GetElementType() 
    {
        return (typeof(ZREQN_ITM));
    }

    /// <summary>
    /// Creates an empty new row of type ZREQN_ITM.
    /// </summary>
    /// <returns>The newZREQN_ITM.</returns>
    public override object CreateNewRow()
    { 
        return new ZREQN_ITM();
    }
     
    /// <summary>
    /// The indexer of the collection.
    /// </summary>
    public ZREQN_ITM this[int index] 
    {
        get 
        {
            return ((ZREQN_ITM)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    /// <summary>
    /// Adds a ZREQN_ITM to the end of the collection.
    /// </summary>
    /// <param name="value">The ZREQN_ITM to be added to the end of the collection.</param>
    /// <returns>The index of the newZREQN_ITM.</returns>
    public int Add(ZREQN_ITM value) 
    {
        return List.Add(value);
    }
        
    /// <summary>
    /// Inserts a ZREQN_ITM into the collection at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index at which value should be inserted.</param>
    /// <param name="value">The ZREQN_ITM to insert.</param>
    public void Insert(int index, ZREQN_ITM value) 
    {
        List.Insert(index, value);
    }
        
    /// <summary>
    /// Searches for the specified ZREQN_ITM and returnes the zero-based index of the first occurrence in the collection.
    /// </summary>
    /// <param name="value">The ZREQN_ITM to locate in the collection.</param>
    /// <returns>The index of the object found or -1.</returns>
    public int IndexOf(ZREQN_ITM value) 
    {
        return List.IndexOf(value);
    }
        
    /// <summary>
    /// Determines wheter an element is in the collection.
    /// </summary>
    /// <param name="value">The ZREQN_ITM to locate in the collection.</param>
    /// <returns>True if found; else false.</returns>
    public bool Contains(ZREQN_ITM value) 
    {
        return List.Contains(value);
    }
        
    /// <summary>
    /// Removes the first occurrence of the specified ZREQN_ITM from the collection.
    /// </summary>
    /// <param name="value">The ZREQN_ITM to remove from the collection.</param>
    public void Remove(ZREQN_ITM value) 
    {
        List.Remove(value);
    }

    /// <summary>
    /// Copies the contents of the ZREQN_ITMTable to the specified one-dimensional array starting at the specified index in the target array.
    /// </summary>
    /// <param name="array">The one-dimensional destination array.</param>           
    /// <param name="index">The zero-based index in array at which copying begins.</param>           
    public void CopyTo(ZREQN_ITM[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
