
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Purchase Requisition Item - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZREQN_ITM" , Length = 177, Length2 = 326)]
  [Serializable]
  public class ZREQN_ITM : SAPStructure
  {
   

    /// <summary>
    /// Purchase requisition number
    /// </summary>
 
    [RfcField(AbapName = "BANFN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("BANFN", Form=XmlSchemaForm.Unqualified)]
    public string Banfn
    { 
       get
       {
          return _Banfn;
       }
       set
       {
          _Banfn = value;
       }
    }
    private string _Banfn;


    /// <summary>
    /// Item number of purchase requisition
    /// </summary>
 
    [RfcField(AbapName = "BNFPO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 10, Offset2 = 20)]
    [XmlElement("BNFPO", Form=XmlSchemaForm.Unqualified)]
    public string Bnfpo
    { 
       get
       {
          return _Bnfpo;
       }
       set
       {
          _Bnfpo = value;
       }
    }
    private string _Bnfpo;


    /// <summary>
    /// Purchasing Group
    /// </summary>
 
    [RfcField(AbapName = "EKGRP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 15, Offset2 = 30)]
    [XmlElement("EKGRP", Form=XmlSchemaForm.Unqualified)]
    public string Ekgrp
    { 
       get
       {
          return _Ekgrp;
       }
       set
       {
          _Ekgrp = value;
       }
    }
    private string _Ekgrp;


    /// <summary>
    /// Purchasing Organization
    /// </summary>
 
    [RfcField(AbapName = "EKORG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 18, Offset2 = 36)]
    [XmlElement("EKORG", Form=XmlSchemaForm.Unqualified)]
    public string Ekorg
    { 
       get
       {
          return _Ekorg;
       }
       set
       {
          _Ekorg = value;
       }
    }
    private string _Ekorg;


    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 22, Offset2 = 44)]
    [XmlElement("MATNR", Form=XmlSchemaForm.Unqualified)]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Short text
    /// </summary>
 
    [RfcField(AbapName = "TXZ01", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 40, Offset2 = 80)]
    [XmlElement("TXZ01", Form=XmlSchemaForm.Unqualified)]
    public string Txz01
    { 
       get
       {
          return _Txz01;
       }
       set
       {
          _Txz01 = value;
       }
    }
    private string _Txz01;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "WERKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 80, Offset2 = 160)]
    [XmlElement("WERKS", Form=XmlSchemaForm.Unqualified)]
    public string Werks
    { 
       get
       {
          return _Werks;
       }
       set
       {
          _Werks = value;
       }
    }
    private string _Werks;


    /// <summary>
    /// Quantity ordered against this purchase requisition
    /// </summary>
 
    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 84, Offset2 = 168)]
    [XmlElement("MENGE", Form=XmlSchemaForm.Unqualified)]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;


    /// <summary>
    /// Base Unit of Measure
    /// </summary>
 
    [RfcField(AbapName = "MEINS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 91, Offset2 = 176)]
    [XmlElement("MEINS", Form=XmlSchemaForm.Unqualified)]
    public string Meins
    { 
       get
       {
          return _Meins;
       }
       set
       {
          _Meins = value;
       }
    }
    private string _Meins;


    /// <summary>
    /// Delivery date
    /// </summary>
 
    [RfcField(AbapName = "LFDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 94, Offset2 = 182)]
    [XmlElement("LFDAT", Form=XmlSchemaForm.Unqualified)]
    public string Lfdat
    { 
       get
       {
          return _Lfdat;
       }
       set
       {
          _Lfdat = value;
       }
    }
    private string _Lfdat;


    /// <summary>
    /// Price
    /// </summary>
 
    [RfcField(AbapName = "PREIS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Length2 = 6, Decimals = 2, Offset = 102, Offset2 = 198)]
    [XmlElement("PREIS", Form=XmlSchemaForm.Unqualified)]
    public Decimal Preis
    { 
       get
       {
          return _Preis;
       }
       set
       {
          _Preis = value;
       }
    }
    private Decimal _Preis;


    /// <summary>
    /// Price Unit
    /// </summary>
 
    [RfcField(AbapName = "PEINH", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Length2 = 3, Offset = 108, Offset2 = 204)]
    [XmlElement("PEINH", Form=XmlSchemaForm.Unqualified)]
    public Decimal Peinh
    { 
       get
       {
          return _Peinh;
       }
       set
       {
          _Peinh = value;
       }
    }
    private Decimal _Peinh;


    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 111, Offset2 = 208)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Item Number of Purchasing Document
    /// </summary>
 
    [RfcField(AbapName = "EBELP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 121, Offset2 = 228)]
    [XmlElement("EBELP", Form=XmlSchemaForm.Unqualified)]
    public string Ebelp
    { 
       get
       {
          return _Ebelp;
       }
       set
       {
          _Ebelp = value;
       }
    }
    private string _Ebelp;


    /// <summary>
    /// Purchase Order Date
    /// </summary>
 
    [RfcField(AbapName = "BEDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 126, Offset2 = 238)]
    [XmlElement("BEDAT", Form=XmlSchemaForm.Unqualified)]
    public string Bedat
    { 
       get
       {
          return _Bedat;
       }
       set
       {
          _Bedat = value;
       }
    }
    private string _Bedat;


    /// <summary>
    /// Quantity ordered against this purchase requisition
    /// </summary>
 
    [RfcField(AbapName = "BSMNG", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 134, Offset2 = 254)]
    [XmlElement("BSMNG", Form=XmlSchemaForm.Unqualified)]
    public Decimal Bsmng
    { 
       get
       {
          return _Bsmng;
       }
       set
       {
          _Bsmng = value;
       }
    }
    private Decimal _Bsmng;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "WAERS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 141, Offset2 = 262)]
    [XmlElement("WAERS", Form=XmlSchemaForm.Unqualified)]
    public string Waers
    { 
       get
       {
          return _Waers;
       }
       set
       {
          _Waers = value;
       }
    }
    private string _Waers;


    /// <summary>
    /// Total value at time of release
    /// </summary>
 
    [RfcField(AbapName = "RLWRT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 146, Offset2 = 272)]
    [XmlElement("RLWRT", Form=XmlSchemaForm.Unqualified)]
    public Decimal Rlwrt
    { 
       get
       {
          return _Rlwrt;
       }
       set
       {
          _Rlwrt = value;
       }
    }
    private Decimal _Rlwrt;


    /// <summary>
    /// Name of requisitioner/requester
    /// </summary>
 
    [RfcField(AbapName = "AFNAM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 154, Offset2 = 280)]
    [XmlElement("AFNAM", Form=XmlSchemaForm.Unqualified)]
    public string Afnam
    { 
       get
       {
          return _Afnam;
       }
       set
       {
          _Afnam = value;
       }
    }
    private string _Afnam;


    /// <summary>
    /// Fixed vendor
    /// </summary>
 
    [RfcField(AbapName = "FLIEF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 166, Offset2 = 304)]
    [XmlElement("FLIEF", Form=XmlSchemaForm.Unqualified)]
    public string Flief
    { 
       get
       {
          return _Flief;
       }
       set
       {
          _Flief = value;
       }
    }
    private string _Flief;


    /// <summary>
    /// Asset class marked for deletion
    /// </summary>
 
    [RfcField(AbapName = "LOEKZ", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 176, Offset2 = 324)]
    [XmlElement("LOEKZ", Form=XmlSchemaForm.Unqualified)]
    public string Loekz
    { 
       get
       {
          return _Loekz;
       }
       set
       {
          _Loekz = value;
       }
    }
    private string _Loekz;

  }

}
