--Delete records from tables
DELETE FROM dbo.[FUNCTION]  ;

--Add records to [FUNCTION]
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0001','Accept/Reject Purchase Order Acknowledgement')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0002','Enquire Purchase Order List')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0003','Print Purchase Order')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0004','Purchase Order Acknowledge By Buyer')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0005','Enquire Purchase Contract List')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0006','Print Purchase Contract')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0007','Create Request for Quotation')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0008','Enquire Quotation')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0009','Print Quotations')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0010','Purchase Order Expediting Process')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0011','View Shortage List')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0012','Print Shortage Report')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0013','Expedite Deliver')
insert into [FUNCTION](FUNCID,FUNCNAM) values('B-0014','Confirm Acknowledgement of Expedite Deliveries')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0001','Acknowledge Purchase Order')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0002','Enquire Purchase Order List')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0003','Print Purchase Order')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0004','Create Delivery Order')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0005','Enquire Delivery Orders')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0006','Print Delivery Order Report')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0007','Acknowledge Purchase Contract')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0008','Enquire Purchase Contract List')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0009','Print Purchase Contract')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0010','Process Quotations')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0011','Enquire Quotation')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0012','Print Quotations')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0013','Acknowledge Expedite Deliveries')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0014','Print Expedite Deliveries List')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0015','Acknowledge Receipt Rejected Goods')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0016','Enquire Goods Rejection')
insert into [FUNCTION](FUNCID,FUNCNAM) values('S-0017','Print Goods Rejection')
insert into [FUNCTION](FUNCID,FUNCNAM) values('U-0001','User List (Reset Password/Maintain Profile)')
insert into [FUNCTION](FUNCID,FUNCNAM) values('U-0002','Update Profile')
insert into [FUNCTION](FUNCID,FUNCNAM) values('U-0003','change password')
insert into [FUNCTION](FUNCID,FUNCNAM) values('W-0001','Enquire Delivery Orders')
insert into [FUNCTION](FUNCID,FUNCNAM) values('W-0002','Print Delivery Order Report')