delete from [FUNCTION]
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0001','Acknowledge Purchase Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0002','Enquire Purchase Order List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0003','Print Purchase Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0004','Create Delivery Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0005','Enquire Delivery Orders')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0006','Print Delivery Order Report')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0007','Acknowledge Purchase Contract')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0008','Enquire Purchase Contract List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0009','Print Purchase Contract')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0010','Process Quotations')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0011','Enquire Quotation')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0012','Print Quotations')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0013','Acknowledge Expedite Deliveries')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0014','Print Expedite Deliveries List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0015','Acknowledge Receipt Rejected Goods')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0016','Enquire Goods Rejection')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('S-0017','Print Goods Rejection')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0001','Accept/Reject Purchase Order Acknowledgement')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0002','Enquire Purchase Order List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0003','Print Purchase Order')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0004','Purchase Order Acknowledge By Buyer')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0005','Enquire Purchase Contract List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0006','Print Purchase Contract')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0007','Create Request for Quotation')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0008','Enquire Quotation')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0009','Print Quotations')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0010','Purchase Order Expediting Process')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0011','View Shortage List')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0012','Print Shortage Report')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0013','Expedite Deliver')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('B-0014','Confirm Acknowledgement of Expedite Deliveries')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('W-0001','Enquire Delivery Orders')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('W-0002','Print Delivery Order Report')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('U-0001','User List (Reset Password/Maintain Profile)')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('U-0002','Update Profile')
Insert [FUNCTION] (FUNCID,FUNCNAM) values('U-0003','change password')
