
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 13/08/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Client SAP proxy class
  /// </summary>
  [WebServiceBinding(Name="dummy.Binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
  [Serializable]
  public class SAPProxy2 : SAPClient
  {
    /// <summary>
    /// Initializes a new SAPProxy2.
    /// </summary>
    public SAPProxy2(){}

    /// <summary>
    /// Initializes a new SAPProxy2 with a new connection based on the specified connection string.
    /// </summary>
    /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
    public SAPProxy2(string connectionString) : base(connectionString){}

    /// <summary>
    /// Initializes a new SAPProxy2 instance and adds it to the given container.
    /// This allows automated connection mananged by VS component designer:
    /// If container is disposed, it will also dispose this SAPClient instance,
    /// which will dispose a contained connection if needed.
    /// </summary>
    /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
    public SAPProxy2(System.ComponentModel.IContainer container) : base(container) {}    
  
    /// <summary>
    /// Exception constant for ABAP-Exception ERRORDELETION
    /// </summary>
    public const string Errordeletion = "ERRORDELETION";
   
    /// <summary>
    /// Remote Function Module ZREMOVECONTRACT.  
    /// Delete the Contracts from ZSCS04 Table
    /// </summary> 
    /// <exception cref="Errordeletion"/>
    [RfcMethod(AbapName = "ZREMOVECONTRACT")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZREMOVECONTRACT",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZREMOVECONTRACT",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZREMOVECONTRACT.Response")]
    public virtual void Zremovecontract (
)
    {
        object[]results = null;
        results = this.SAPInvoke("Zremovecontract",new object[] {
                             });

    }

  } 

}
