
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 31/12/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Client SAP proxy class
  /// </summary>
  [WebServiceBinding(Name="dummy.Binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
  [Serializable]
  public class SAPProxy5 : SAPClient
  {
    /// <summary>
    /// Initializes a new SAPProxy5.
    /// </summary>
    public SAPProxy5(){}

    /// <summary>
    /// Initializes a new SAPProxy5 with a new connection based on the specified connection string.
    /// </summary>
    /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
    public SAPProxy5(string connectionString) : base(connectionString){}

    /// <summary>
    /// Initializes a new SAPProxy5 instance and adds it to the given container.
    /// This allows automated connection mananged by VS component designer:
    /// If container is disposed, it will also dispose this SAPClient instance,
    /// which will dispose a contained connection if needed.
    /// </summary>
    /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
    public SAPProxy5(System.ComponentModel.IContainer container) : base(container) {}    
  
    /// <summary>
    /// Exception constant for ABAP-Exception RECORDNOTFOUND
    /// </summary>
    public const string Recordnotfound = "RECORDNOTFOUND";
   
    /// <summary>
    /// Remote Function Module ZRETRIEVESUPPLIER.  
    /// Retrieve Supplier Details
    /// </summary>
    /// <param name="Supplier_Master">Supplier Details - Work Area</param> 
    /// <exception cref="Recordnotfound"/>
    [RfcMethod(AbapName = "ZRETRIEVESUPPLIER")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZRETRIEVESUPPLIER",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZRETRIEVESUPPLIER",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZRETRIEVESUPPLIER.Response")]
    public virtual void Zretrievesupplier (

     [RfcParameter(AbapName = "SUPPLIER_MASTER",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("SUPPLIER_MASTER", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     ref ZSUPPLIERTable Supplier_Master)
    {
        object[]results = null;
        results = this.SAPInvoke("Zretrievesupplier",new object[] {
                            Supplier_Master });
        Supplier_Master = (ZSUPPLIERTable) results[0];

    }

  } 

}
