
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 01/01/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Client SAP proxy class
  /// </summary>
  [WebServiceBinding(Name="dummy.Binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
  [Serializable]
  public class SAPProxy4 : SAPClient
  {
    /// <summary>
    /// Initializes a new SAPProxy4.
    /// </summary>
    public SAPProxy4(){}

    /// <summary>
    /// Initializes a new SAPProxy4 with a new connection based on the specified connection string.
    /// </summary>
    /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
    public SAPProxy4(string connectionString) : base(connectionString){}

    /// <summary>
    /// Initializes a new SAPProxy4 instance and adds it to the given container.
    /// This allows automated connection mananged by VS component designer:
    /// If container is disposed, it will also dispose this SAPClient instance,
    /// which will dispose a contained connection if needed.
    /// </summary>
    /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
    public SAPProxy4(System.ComponentModel.IContainer container) : base(container) {}    
  
    /// <summary>
    /// Exception constant for ABAP-Exception RECORDNOTFOUND
    /// </summary>
    public const string Recordnotfound = "RECORDNOTFOUND";
   
    /// <summary>
    /// Remote Function Module ZRETRIEVEREQUIREMENT.  
    /// Retrieve Material Requirement
    /// </summary>
    /// <param name="Material_Requirement">Material Requirement Details - Work Area</param> 
    /// <exception cref="Recordnotfound"/>
    [RfcMethod(AbapName = "ZRETRIEVEREQUIREMENT")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZRETRIEVEREQUIREMENT",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZRETRIEVEREQUIREMENT",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZRETRIEVEREQUIREMENT.Response")]
    public virtual void Zretrieverequirement (

     [RfcParameter(AbapName = "MATERIAL_REQUIREMENT",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("MATERIAL_REQUIREMENT", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     ref ZMATL_REQUIRETable Material_Requirement)
    {
        object[]results = null;
        results = this.SAPInvoke("Zretrieverequirement",new object[] {
                            Material_Requirement });
        Material_Requirement = (ZMATL_REQUIRETable) results[0];

    }

    /// <summary>
    /// Remote Function Module ZRETRIEVESTOCK.  
    /// Retrieve Material Stock
    /// </summary>
    /// <param name="Material_Stock">Material Stock Balance Details - Work Area</param> 
    /// <exception cref="Recordnotfound"/>
    [RfcMethod(AbapName = "ZRETRIEVESTOCK")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZRETRIEVESTOCK",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZRETRIEVESTOCK",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZRETRIEVESTOCK.Response")]
    public virtual void Zretrievestock (

     [RfcParameter(AbapName = "MATERIAL_STOCK",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("MATERIAL_STOCK", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
     ref ZMATL_STOCKTable Material_Stock)
    {
        object[]results = null;
        results = this.SAPInvoke("Zretrievestock",new object[] {
                            Material_Stock });
        Material_Stock = (ZMATL_STOCKTable) results[0];

    }

  } 

}
