
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 11/08/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Contract Header Details - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZCONTRACT_HDR" , Length = 132, Length2 = 252)]
  [Serializable]
  public class ZCONTRACT_HDR : SAPStructure
  {
   

    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Purchase Order Date
    /// </summary>
 
    [RfcField(AbapName = "BEDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 10, Offset2 = 20)]
    [XmlElement("BEDAT", Form=XmlSchemaForm.Unqualified)]
    public string Bedat
    { 
       get
       {
          return _Bedat;
       }
       set
       {
          _Bedat = value;
       }
    }
    private string _Bedat;


    /// <summary>
    /// Purchasing document category
    /// </summary>
 
    [RfcField(AbapName = "BSTYP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 18, Offset2 = 36)]
    [XmlElement("BSTYP", Form=XmlSchemaForm.Unqualified)]
    public string Bstyp
    { 
       get
       {
          return _Bstyp;
       }
       set
       {
          _Bstyp = value;
       }
    }
    private string _Bstyp;


    /// <summary>
    /// Order type (Purchasing)
    /// </summary>
 
    [RfcField(AbapName = "BSART", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 19, Offset2 = 38)]
    [XmlElement("BSART", Form=XmlSchemaForm.Unqualified)]
    public string Bsart
    { 
       get
       {
          return _Bsart;
       }
       set
       {
          _Bsart = value;
       }
    }
    private string _Bsart;


    /// <summary>
    /// Name of Person who Created the Object
    /// </summary>
 
    [RfcField(AbapName = "ERNAM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 12, Length2 = 24, Offset = 23, Offset2 = 46)]
    [XmlElement("ERNAM", Form=XmlSchemaForm.Unqualified)]
    public string Ernam
    { 
       get
       {
          return _Ernam;
       }
       set
       {
          _Ernam = value;
       }
    }
    private string _Ernam;


    /// <summary>
    /// Account Number of Vendor or Creditor
    /// </summary>
 
    [RfcField(AbapName = "LIFNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 35, Offset2 = 70)]
    [XmlElement("LIFNR", Form=XmlSchemaForm.Unqualified)]
    public string Lifnr
    { 
       get
       {
          return _Lifnr;
       }
       set
       {
          _Lifnr = value;
       }
    }
    private string _Lifnr;


    /// <summary>
    /// Terms of payment key
    /// </summary>
 
    [RfcField(AbapName = "ZTERM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 45, Offset2 = 90)]
    [XmlElement("ZTERM", Form=XmlSchemaForm.Unqualified)]
    public string Zterm
    { 
       get
       {
          return _Zterm;
       }
       set
       {
          _Zterm = value;
       }
    }
    private string _Zterm;


    /// <summary>
    /// Purchasing Group
    /// </summary>
 
    [RfcField(AbapName = "EKGRP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 49, Offset2 = 98)]
    [XmlElement("EKGRP", Form=XmlSchemaForm.Unqualified)]
    public string Ekgrp
    { 
       get
       {
          return _Ekgrp;
       }
       set
       {
          _Ekgrp = value;
       }
    }
    private string _Ekgrp;


    /// <summary>
    /// Currency Key
    /// </summary>
 
    [RfcField(AbapName = "WAERS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Length2 = 10, Offset = 52, Offset2 = 104)]
    [XmlElement("WAERS", Form=XmlSchemaForm.Unqualified)]
    public string Waers
    { 
       get
       {
          return _Waers;
       }
       set
       {
          _Waers = value;
       }
    }
    private string _Waers;


    /// <summary>
    /// Exchange rate
    /// </summary>
 
    [RfcField(AbapName = "WKURS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 5, Length2 = 5, Decimals = 5, Offset = 57, Offset2 = 114)]
    [XmlElement("WKURS", Form=XmlSchemaForm.Unqualified)]
    public Decimal Wkurs
    { 
       get
       {
          return _Wkurs;
       }
       set
       {
          _Wkurs = value;
       }
    }
    private Decimal _Wkurs;


    /// <summary>
    /// Start of validity period
    /// </summary>
 
    [RfcField(AbapName = "KDATB", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 62, Offset2 = 120)]
    [XmlElement("KDATB", Form=XmlSchemaForm.Unqualified)]
    public string Kdatb
    { 
       get
       {
          return _Kdatb;
       }
       set
       {
          _Kdatb = value;
       }
    }
    private string _Kdatb;


    /// <summary>
    /// End of validity period
    /// </summary>
 
    [RfcField(AbapName = "KDATE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 70, Offset2 = 136)]
    [XmlElement("KDATE", Form=XmlSchemaForm.Unqualified)]
    public string Kdate
    { 
       get
       {
          return _Kdate;
       }
       set
       {
          _Kdate = value;
       }
    }
    private string _Kdate;


    /// <summary>
    /// Salesperson responsible in the event of queries
    /// </summary>
 
    [RfcField(AbapName = "VERKF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 78, Offset2 = 152)]
    [XmlElement("VERKF", Form=XmlSchemaForm.Unqualified)]
    public string Verkf
    { 
       get
       {
          return _Verkf;
       }
       set
       {
          _Verkf = value;
       }
    }
    private string _Verkf;


    /// <summary>
    /// First telephone number
    /// </summary>
 
    [RfcField(AbapName = "TELF1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 108, Offset2 = 212)]
    [XmlElement("TELF1", Form=XmlSchemaForm.Unqualified)]
    public string Telf1
    { 
       get
       {
          return _Telf1;
       }
       set
       {
          _Telf1 = value;
       }
    }
    private string _Telf1;


    /// <summary>
    /// Cumulative planned value
    /// </summary>
 
    [RfcField(AbapName = "KTWRT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 124, Offset2 = 244)]
    [XmlElement("KTWRT", Form=XmlSchemaForm.Unqualified)]
    public Decimal Ktwrt
    { 
       get
       {
          return _Ktwrt;
       }
       set
       {
          _Ktwrt = value;
       }
    }
    private Decimal _Ktwrt;

  }

}
