
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/01/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{

  /// <summary>
  /// Purchase order Close and Completion Status - Work Area
  /// </summary>
  [RfcStructure(AbapName ="ZORDER_CLOSE" , Length = 17, Length2 = 34)]
  [Serializable]
  public class ZORDER_CLOSE : SAPStructure
  {
   

    /// <summary>
    /// Purchasing Document Number
    /// </summary>
 
    [RfcField(AbapName = "EBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("EBELN", Form=XmlSchemaForm.Unqualified)]
    public string Ebeln
    { 
       get
       {
          return _Ebeln;
       }
       set
       {
          _Ebeln = value;
       }
    }
    private string _Ebeln;


    /// <summary>
    /// Item Number of Purchasing Document
    /// </summary>
 
    [RfcField(AbapName = "EBELP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 10, Offset2 = 20)]
    [XmlElement("EBELP", Form=XmlSchemaForm.Unqualified)]
    public string Ebelp
    { 
       get
       {
          return _Ebelp;
       }
       set
       {
          _Ebelp = value;
       }
    }
    private string _Ebelp;


    /// <summary>
    /// Asset class marked for deletion
    /// </summary>
 
    [RfcField(AbapName = "POSTS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 15, Offset2 = 30)]
    [XmlElement("POSTS", Form=XmlSchemaForm.Unqualified)]
    public string Posts
    { 
       get
       {
          return _Posts;
       }
       set
       {
          _Posts = value;
       }
    }
    private string _Posts;


    /// <summary>
    /// Asset class marked for deletion
    /// </summary>
 
    [RfcField(AbapName = "ITSTS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 16, Offset2 = 32)]
    [XmlElement("ITSTS", Form=XmlSchemaForm.Unqualified)]
    public string Itsts
    { 
       get
       {
          return _Itsts;
       }
       set
       {
          _Itsts = value;
       }
    }
    private string _Itsts;

  }

}
