
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 11/08/2009
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SAPInterface
{
  /// <summary>
  /// A typed collection of ZCONTRACT_HDR elements.
  /// </summary>
  [Serializable]
  public class ZCONTRACT_HDRTable : SAPTable 
  {
  
    /// <summary>
    /// Returns the element type ZCONTRACT_HDR.
    /// </summary>
    /// <returns>The type ZCONTRACT_HDR.</returns>
    public override Type GetElementType() 
    {
        return (typeof(ZCONTRACT_HDR));
    }

    /// <summary>
    /// Creates an empty new row of type ZCONTRACT_HDR.
    /// </summary>
    /// <returns>The newZCONTRACT_HDR.</returns>
    public override object CreateNewRow()
    { 
        return new ZCONTRACT_HDR();
    }
     
    /// <summary>
    /// The indexer of the collection.
    /// </summary>
    public ZCONTRACT_HDR this[int index] 
    {
        get 
        {
            return ((ZCONTRACT_HDR)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    /// <summary>
    /// Adds a ZCONTRACT_HDR to the end of the collection.
    /// </summary>
    /// <param name="value">The ZCONTRACT_HDR to be added to the end of the collection.</param>
    /// <returns>The index of the newZCONTRACT_HDR.</returns>
    public int Add(ZCONTRACT_HDR value) 
    {
        return List.Add(value);
    }
        
    /// <summary>
    /// Inserts a ZCONTRACT_HDR into the collection at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index at which value should be inserted.</param>
    /// <param name="value">The ZCONTRACT_HDR to insert.</param>
    public void Insert(int index, ZCONTRACT_HDR value) 
    {
        List.Insert(index, value);
    }
        
    /// <summary>
    /// Searches for the specified ZCONTRACT_HDR and returnes the zero-based index of the first occurrence in the collection.
    /// </summary>
    /// <param name="value">The ZCONTRACT_HDR to locate in the collection.</param>
    /// <returns>The index of the object found or -1.</returns>
    public int IndexOf(ZCONTRACT_HDR value) 
    {
        return List.IndexOf(value);
    }
        
    /// <summary>
    /// Determines wheter an element is in the collection.
    /// </summary>
    /// <param name="value">The ZCONTRACT_HDR to locate in the collection.</param>
    /// <returns>True if found; else false.</returns>
    public bool Contains(ZCONTRACT_HDR value) 
    {
        return List.Contains(value);
    }
        
    /// <summary>
    /// Removes the first occurrence of the specified ZCONTRACT_HDR from the collection.
    /// </summary>
    /// <param name="value">The ZCONTRACT_HDR to remove from the collection.</param>
    public void Remove(ZCONTRACT_HDR value) 
    {
        List.Remove(value);
    }

    /// <summary>
    /// Copies the contents of the ZCONTRACT_HDRTable to the specified one-dimensional array starting at the specified index in the target array.
    /// </summary>
    /// <param name="array">The one-dimensional destination array.</param>           
    /// <param name="index">The zero-based index in array at which copying begins.</param>           
    public void CopyTo(ZCONTRACT_HDR[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
